create table adresse (id bigint not null auto_increment, hausnummer varchar(255), ort varchar(255), plz varchar(255), strasse varchar(255), gebiet_id bigint, primary key (id)) engine=InnoDB;
create table auftrag (id bigint not null auto_increment, auftragstext varchar(4000), beginndatum datetime(6), enddatum datetime(6), erstellungsdatum datetime(6), nummer varchar(255), status integer, adresse_id bigint, angelegt_von_id bigint, bauherr_benutzer_id bigint, versicherungsnehmer_benutzer_id bigint, primary key (id)) engine=InnoDB;
create table auftrag_notiz (auftrag_id bigint not null, notiz_id bigint not null) engine=InnoDB;
create table auftrag_teilauftrag (auftrag_id bigint not null, teilauftrag_id bigint not null) engine=InnoDB;
create table backoffice_mitarbeiter (benutzer_id bigint not null, primary key (benutzer_id)) engine=InnoDB;
create table bauherr (benutzer_id bigint not null, primary key (benutzer_id)) engine=InnoDB;;
create table benutzer (id bigint not null auto_increment, anrede varchar(255), e_mailadresse varchar(255), enabled bit not null, letzte_anmeldung datetime(6), nachname varchar(255), passwort varchar(255), telefonnummer varchar(255), vorname varchar(255), primary key (id)) engine=InnoDB;
create table berater (benutzer_id bigint not null, primary key (benutzer_id)) engine=InnoDB;
create table gebiet (id bigint not null auto_increment, bereich varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table gebiet_bauherr (bauherr_id bigint not null, gebiet_id bigint not null) engine=InnoDB;
create table gebiet_berater (berater_id bigint not null, gebiet_id bigint not null) engine=InnoDB;
create table gebiet_handwerker (handwerker_id bigint not null, gebiet_id bigint not null) engine=InnoDB;
create table gewerk (id bigint not null auto_increment, kuerzel varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table gewerk_handwerker (handwerker_id bigint not null, gewerk_id bigint not null) engine=InnoDB;
create table handwerker (benutzer_id bigint not null, primary key (benutzer_id)) engine=InnoDB;
create table itmitarbeiter (benutzer_id bigint not null, primary key (benutzer_id)) engine=InnoDB;
create table notiz (id bigint not null auto_increment, date datetime(6), text varchar(4000), benutzer_id bigint, primary key (id)) engine=InnoDB;
create table teilauftrag (id bigint not null auto_increment, auftragstext varchar(4000), beginndatum datetime(6), enddatum datetime(6), nummer varchar(255), status integer, auftrag_id bigint, gewerk_id bigint, handwerker_benutzer_id bigint, primary key (id)) engine=InnoDB;
create table teilauftrag_notiz (teilauftrag_id bigint not null, notiz_id bigint not null) engine=InnoDB;
create table versicherungsnehmer (policennummer varchar(255), benutzer_id bigint not null, adresse_id bigint, primary key (benutzer_id)) engine=InnoDB;
alter table auftrag add constraint UX_Nummer unique (nummer);
alter table auftrag_notiz add constraint UK_m16sjhn2ind92tv4curpqxyh3 unique (notiz_id);
alter table auftrag_teilauftrag add constraint UK_lw1ewm2px7snigc59o77ijmsw unique (teilauftrag_id);
alter table teilauftrag add constraint UX_Nummer unique (nummer);
alter table teilauftrag_notiz add constraint UK_7ov6oyqdmr9bg55bxs2vx9a4b unique (notiz_id);
alter table adresse add constraint FKpasgjxi9xisq96celjj8wc0hf foreign key (gebiet_id) references gebiet (id);
alter table auftrag add constraint FKf8vp1bdbyt0d76ikcrh91878f foreign key (adresse_id) references adresse (id);
alter table auftrag add constraint FKls3xv97h6n2fugg61bftrfgpa foreign key (angelegt_von_id) references benutzer (id);
alter table auftrag add constraint FK1l721ypikfq8i0u3kf36o3jp7 foreign key (bauherr_benutzer_id) references bauherr (benutzer_id);
alter table auftrag add constraint FKjucmac7ps8xbkacpmax9oejqe foreign key (versicherungsnehmer_benutzer_id) references versicherungsnehmer (benutzer_id);
alter table auftrag_notiz add constraint FKfjk4wpkbwblesfbl539d929qa foreign key (notiz_id) references notiz (id);
alter table auftrag_notiz add constraint FKrmxww868tkixsyg7tso415gt7 foreign key (auftrag_id) references auftrag (id);
alter table auftrag_teilauftrag add constraint FKq33ekgojnl6x12tgj9hcl14qy foreign key (teilauftrag_id) references teilauftrag (id);
alter table auftrag_teilauftrag add constraint FKfnyu6sdx92cp4fu8pk6fr18jd foreign key (auftrag_id) references auftrag (id);
alter table backoffice_mitarbeiter add constraint FKpsak54ki6d97vw4vjlnfjocx0 foreign key (benutzer_id) references benutzer (id);
alter table bauherr add constraint FK2ome0mmiorrv5tjj6d5jiswih foreign key (benutzer_id) references benutzer (id);
alter table berater add constraint FK12mr5sxu4r14walnwyp3vl9k8 foreign key (benutzer_id) references benutzer (id);
alter table gebiet_bauherr add constraint FKetdcxiahiff2ig78v28n1anb1 foreign key (gebiet_id) references gebiet (id);
alter table gebiet_bauherr add constraint FKtmudnx737wiiqawnpadnkyjcv foreign key (bauherr_id) references bauherr (benutzer_id);
alter table gebiet_berater add constraint FKqvc311pn6ankc54hysong7vef foreign key (gebiet_id) references gebiet (id);
alter table gebiet_berater add constraint FKd9lroov3mf8gen17gaytcrsua foreign key (berater_id) references berater (benutzer_id);
alter table gebiet_handwerker add constraint FK3c3xam9nmebek8tawpjj9qh1r foreign key (gebiet_id) references gebiet (id);
alter table gebiet_handwerker add constraint FK21jlqf1an9acb6ffq3jgmosyb foreign key (handwerker_id) references handwerker (benutzer_id);
alter table gewerk_handwerker add constraint FKbrrficwy05gu6ab0efboodwxv foreign key (gewerk_id) references gewerk (id);
alter table gewerk_handwerker add constraint FK2m6sf7f9kty75ruf8jhpdne31 foreign key (handwerker_id) references handwerker (benutzer_id);
alter table handwerker add constraint FKe5ja8d6ncnid52oh43nyvm3js foreign key (benutzer_id) references benutzer (id);
alter table itmitarbeiter add constraint FKlu3ygc8o7vwh07ki9nnfklq1e foreign key (benutzer_id) references benutzer (id);
alter table notiz add constraint FK6vgvfsu1aetjp8oq7yokslgu1 foreign key (benutzer_id) references benutzer (id);
alter table teilauftrag add constraint FK5mxa3peivrmpx29qop0nsjlod foreign key (auftrag_id) references auftrag (id);
alter table teilauftrag add constraint FKfscd1ph6br5o6mfp8xy4ttavf foreign key (gewerk_id) references gewerk (id);
alter table teilauftrag add constraint FKmmeagi4ydo4d4487g12325thx foreign key (handwerker_benutzer_id) references handwerker (benutzer_id);
alter table teilauftrag_notiz add constraint FKnvmq3t4wonh3wk055dovrajv2 foreign key (notiz_id) references notiz (id);
alter table teilauftrag_notiz add constraint FK509cf2l0amvw9kcvrphtpb3id foreign key (teilauftrag_id) references teilauftrag (id);
alter table versicherungsnehmer add constraint FK8oa1akynbbin7td5gxpnp77tw foreign key (adresse_id) references adresse (id);
alter table versicherungsnehmer add constraint FK2rcs6y11aswocjkys17fd5898 foreign key (benutzer_id) references benutzer (id);
