INSERT INTO gewerk(name,kuerzel)
VALUES 
('Erdarbeiten','Erde'),
('Bohrarbeiten','Bohr'),
('Arbeiten zum Ausbau von Bohrungen','Ausbau Bohr'),
('Verbauarbeiten','Verbau'),
('Ramm-, Rüttel- und Pressarbeiten','RRP-Arbeiten'),
('Wasserhaltungsarbeiten','Wasser haltung'),
('Entwässerungskanalarbeiten','Entwässerungskanal'),
('Druckrohrleitungsarbeiten außerhalb von Gebäuden 249','Druckrohr außerhalb Gebäuden'),
('Drän- und Versickerarbeiten','Versickerarbeiten'),
('Einpressarbeiten','Einpress'),
('Nassbaggerarbeiten','Nassbagger'),
('Untertagebauarbeiten','Untertagebau'),
('Schlitzwandarbeiten mit stützenden Flüssigkeiten','Schlitzwand'),
('Spritzbetonarbeiten','Spritzbeton'),
('Rohrvortriebsarbeiten','Rohrvortrieb'),
('Landschaftsbauarbeiten',''),
('Düsenstrahlarbeiten','Düsenstrahl'),
('Kabelleitungstiefbauarbeiten','Kabelleitungtief'),
('Kampfmittelräumarbeiten','Kampf'),
('Horizontalspülbohrarbeiten','Horizontalspühlbohr'),
('Renovierungsarbeiten an Entwässerungskanälen','RenovEntwässerung'),
('Mauerarbeiten','Mauer'),
('Betonarbeiten','Beton'),
('Naturwerksteinarbeiten','Naturwerkstein'),
('Betonwerksteinarbeiten','Betonwerkstein'),
('Zimmer- und Holzbauarbeiten','Zimmer- und Holzbau'),
('Stahlbauarbeiten','Stahlbau'),
('Abdichtungsarbeiten','Abdichtung'),
('Dachdeckungsarbeiten','Dachdeckung'),
('Klempnerarbeiten','Klempner'),
('Trockenbauarbeiten','Trockenbau'),
('Wärmedämm-Verbundsysteme','Wärmedämm-Verbund'),
('Betonerhaltungsarbeiten','Betonerhaltung'),
('Putz- und Stuckarbeiten','Putz- und Stuck'),
('Fliesen- und Plattenarbeiten','Fliesen- und Platten'),
('Estricharbeiten','Estrich'),
('Gussasphaltarbeiten','Gussasphalt'),
('Tischlerarbeiten','Tischler'),
('Parkett- und Holzpflasterarbeiten','Parkett- und Holzpflaster'),
('Beschlagarbeiten','Beschlag'),
('Rollladenarbeiten','Rollladen'),
('Metallbauarbeiten','Metallbau'),
('Verglasungsarbeiten','Verglasungs'),
('Maler- und Lackierarbeiten - Beschichtungen','Maler- und Lackierarbeiten - Beschi'),
('Korrosionsschutzarbeiten an Stahlbauten','Korrosionsschutzarbeiten an Sta'),
('Bodenbelagarbeiten','Bodenbelag'),
('Tapezierarbeiten','Tapezier'),
('Raumlufttechnische Anlagen','Raumlufttechnische'),
('Heizanlagen und zentrale Wassererwärmungs-anlagen','Heizanlagen'),
('Gas-, Wasser- und Entwässerungsanlagen innerhalb von Gebäuden','Gas-, Wasser- und Entwässerungsanlagen innerhalb von'),
('Elektro-, Sicherheits- und Informationstechnische Anlagen','Elektro'),
('Blitzschutz-, Überspannungsschutz- und Erdungs- anlagen','Blitz'),
('Aufzugsanlagen, Fahrtreppen und Fahrsteige sowie Förderanlagen','Aufzugsanlagensystem'),
('Gebäudeautomation','Gebäudeautomation'),
('Dämm- und Brandschutzarbeiten an technischen Anlagen','Dämmarbeiten'),
('Gerüstarbeiten','Gerüst'),
('Abbruch- und Rückbauarbeiten','Abbruch- und Rückbau');